import { useCallback, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, TextInput, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as Sentry from '@sentry/react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Plus } from 'lucide-react-native';
import { Text } from '@/components/ui/Text';
import { Button } from '@/components/ui/Button';
import { useBusinessCampaigns, useCreateCampaign, useMyBusiness, usePublishCampaign } from '@/hooks/queries/useBusinessStudio';
import { useAuthStore } from '@/stores/authStore';
import { uploadWithRetry } from '@/services/uploadQueue';
import { colors } from '@/constants/colors';
import type { BusinessCampaign } from '@/services/api/schemas/business.schema';

export default function CampaignsScreen() { const insets = useSafeAreaInsets(); const { data: workspace } = useMyBusiness(); const query = useBusinessCampaigns(workspace?.id); const create = useCreateCampaign(workspace?.id ?? ''); const publish = usePublishCampaign(workspace?.id ?? ''); const user = useAuthStore((state) => state.user); const [creating, setCreating] = useState(false); const [title, setTitle] = useState('');
  const pickAndCreate = useCallback(async () => { if (!workspace?.id || !user?.id || !title.trim()) return; try { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images', 'videos'], quality: 0.9 }); const asset = result.assets?.[0]; if (result.canceled || !asset) return; const mediaType = asset.type === 'video' ? 'video' : 'image'; const upload = await uploadWithRetry(asset.uri, 'campaigns', user.id); await create.mutateAsync({ title: title.trim(), mediaUrl: upload.downloadUrl, mediaType }); setTitle(''); setCreating(false); } catch (error) { Sentry.captureException(error); Alert.alert('Campaign not created', 'Please try again.'); } }, [create, title, user?.id, workspace?.id]);
  const confirmPublish = useCallback((campaign: BusinessCampaign) => { Alert.alert('Publish campaign?', `This will send “${campaign.title}” to the current eligible audience.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Publish', onPress: () => publish.mutate(campaign.id) }]); }, [publish]);
  const renderItem = useCallback(({ item }: { item: BusinessCampaign }) => <View style={styles.card}><Text variant="subtitle" style={styles.title}>{item.title}</Text><Text variant="caption" style={styles.muted}>{item.state.toUpperCase()} · {item.counts?.delivered ?? 0}/{item.audienceSnapshotCount} delivered</Text>{item.state === 'draft' && <Button size="sm" onPress={() => confirmPublish(item)} loading={publish.isPending}>Publish</Button>}</View>, [confirmPublish, publish.isPending]);
  return <View style={[styles.page, { paddingTop: insets.top + 16 }]}><View style={styles.header}><Text variant="title" style={styles.title}>Campaigns</Text><Pressable onPress={() => setCreating(true)} accessibilityLabel="Create campaign" accessibilityRole="button"><Plus color={colors.primary} size={28} /></Pressable></View>{creating && <View style={styles.composer}><TextInput value={title} onChangeText={setTitle} placeholder="Campaign title" placeholderTextColor={colors.textTertiary} style={styles.input} accessibilityLabel="Campaign title" /><Button onPress={pickAndCreate} loading={create.isPending} disabled={!title.trim()}>Choose media and save draft</Button></View>}<FlatList data={query.data ?? []} renderItem={renderItem} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text variant="body" style={styles.muted}>No campaigns yet.</Text>} /></View>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background, paddingHorizontal: 20 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }, title: { color: colors.textPrimary }, muted: { color: colors.textSecondary }, composer: { backgroundColor: colors.surface, padding: 16, borderRadius: 16, gap: 12, marginBottom: 16 }, input: { color: colors.textPrimary, borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 12 }, list: { gap: 12, paddingBottom: 30 }, card: { backgroundColor: colors.surface, borderRadius: 16, padding: 16, gap: 10 } });
