import { ScrollView, StyleSheet, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useMyBusiness, useBusinessOverview } from '@/hooks/queries/useBusinessStudio';
import { QueryState } from '@/components/ui/QueryState';
import { Skeleton } from '@/components/ui/Skeleton';
import { Text } from '@/components/ui/Text';
import { colors } from '@/constants/colors';

export default function BusinessOverviewScreen() { const insets = useSafeAreaInsets(); const { data: workspace } = useMyBusiness(); const query = useBusinessOverview(workspace?.id); return <ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 20 }]} style={styles.page}><Text variant="title" style={styles.title}>{workspace?.displayName ?? 'Business Studio'}</Text><QueryState data={query.data} isLoading={query.isLoading} isError={query.isError} refetch={query.refetch} skeleton={<Skeleton width="100%" height={180} borderRadius={16} />} isEmpty={() => false}>{(overview) => <><View style={styles.card}><Text variant="caption" style={styles.muted}>PILOT AUDIENCE</Text><Text variant="title" style={styles.number}>{overview.followerCount}</Text><Text variant="body" style={styles.muted}>followers</Text></View>{overview.activeCampaign ? <View style={styles.card}><Text variant="caption" style={styles.muted}>ACTIVE CAMPAIGN</Text><Text variant="subtitle" style={styles.title}>{overview.activeCampaign.title}</Text><Text variant="body" style={styles.muted}>{overview.activeCampaign.counts?.delivered ?? 0} delivered · {overview.activeCampaign.counts?.reacted ?? 0} reacted</Text></View> : <View style={styles.card}><Text variant="subtitle" style={styles.title}>No campaign yet</Text><Text variant="body" style={styles.muted}>Create a draft from Campaigns to begin.</Text></View>}</>}</QueryState></ScrollView>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { padding: 20, gap: 16 }, title: { color: colors.textPrimary }, card: { backgroundColor: colors.surface, borderRadius: 16, padding: 20, gap: 8 }, muted: { color: colors.textSecondary }, number: { color: colors.primary, fontSize: 42 } });
