import { useCallback, useMemo, useState } from 'react';
import { FlatList, Image, Pressable, StyleSheet, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Text } from '@/components/ui/Text';
import { useBusinessCampaigns, useCampaignReactions, useMyBusiness, useReactionSelection } from '@/hooks/queries/useBusinessStudio';
import { colors } from '@/constants/colors';
import type { CampaignReaction } from '@/services/api/schemas/business.schema';

export default function ReactionsScreen() { const insets = useSafeAreaInsets(); const { data: workspace } = useMyBusiness(); const campaigns = useBusinessCampaigns(workspace?.id); const campaignId = campaigns.data?.[0]?.id; const [filter, setFilter] = useState<'newest' | 'selected'>('newest'); const reactions = useCampaignReactions(workspace?.id, campaignId, filter); const selection = useReactionSelection(workspace?.id ?? '', campaignId ?? ''); const data = useMemo(() => reactions.data?.data ?? [], [reactions.data]); const toggleFilter = useCallback(() => setFilter((current) => current === 'newest' ? 'selected' : 'newest'), []); const renderItem = useCallback(({ item }: { item: CampaignReaction }) => <Pressable style={styles.tile} onPress={() => selection.mutate({ reactionId: item.id, selected: !item.selected })} accessibilityLabel={`Select reaction from ${item.actor.displayName}`} accessibilityRole="button"><Image source={{ uri: item.actor.avatarUrl ?? undefined }} style={styles.avatar} accessibilityRole="image" /><Text variant="caption" style={styles.name}>{item.actor.displayName}</Text><Text variant="caption" style={item.selected ? styles.selected : styles.unselected}>{item.selected ? 'Selected' : 'Select'}</Text></Pressable>, [selection]); return <View style={[styles.page, { paddingTop: insets.top + 16 }]}><View style={styles.header}><Text variant="title" style={styles.title}>Reactions</Text><Pressable onPress={toggleFilter} accessibilityLabel="Change reaction filter" accessibilityRole="button"><Text variant="body" style={styles.filter}>{filter === 'newest' ? 'Newest' : 'Selected'}</Text></Pressable></View><FlatList data={data} renderItem={renderItem} keyExtractor={(item) => item.id} numColumns={2} columnWrapperStyle={styles.columns} contentContainerStyle={styles.list} ListEmptyComponent={<Text variant="body" style={styles.muted}>Choose a campaign with reactions to curate.</Text>} /></View>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background, paddingHorizontal: 20 }, header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 }, title: { color: colors.textPrimary }, filter: { color: colors.primary }, columns: { gap: 12 }, list: { gap: 12 }, tile: { flex: 1, backgroundColor: colors.surface, borderRadius: 16, minHeight: 150, justifyContent: 'flex-end', padding: 14, gap: 4 }, avatar: { position: 'absolute', top: 14, left: 14, width: 40, height: 40, borderRadius: 20, backgroundColor: colors.border }, name: { color: colors.textPrimary }, selected: { color: colors.primary }, unselected: { color: colors.textSecondary }, muted: { color: colors.textSecondary, textAlign: 'center', marginTop: 40 } });
