import { api } from '@/services/api';
import { validateResponse } from './schemas/common.schema';
import { BusinessCampaignSchema, BusinessOverviewSchema, BusinessWorkspaceSchema, CampaignReactionPageSchema, type BusinessCampaign, type BusinessOverview, type BusinessWorkspace } from './schemas/business.schema';

export async function getMyBusiness(): Promise<BusinessWorkspace | null> { const { data } = await api.get<unknown>('/businesses/mine'); return data ? validateResponse(BusinessWorkspaceSchema, data, 'getMyBusiness') : null; }
export async function getOverview(workspaceId: string): Promise<BusinessOverview> { const { data } = await api.get<unknown>(`/businesses/${workspaceId}/overview`); return validateResponse(BusinessOverviewSchema, data, 'getBusinessOverview'); }
export async function getCampaigns(workspaceId: string): Promise<BusinessCampaign[]> { const { data } = await api.get<unknown[]>(`/businesses/${workspaceId}/campaigns`); return data.map((item) => validateResponse(BusinessCampaignSchema, item, 'getBusinessCampaigns')); }
export async function createCampaign(workspaceId: string, input: { title: string; mediaUrl: string; mediaType: 'image' | 'video'; textOverlay?: string }): Promise<BusinessCampaign> { const { data } = await api.post<unknown>(`/businesses/${workspaceId}/campaigns`, input); return validateResponse(BusinessCampaignSchema, data, 'createBusinessCampaign'); }
export async function publishCampaign(workspaceId: string, campaignId: string): Promise<BusinessCampaign> { const { data } = await api.post<unknown>(`/businesses/${workspaceId}/campaigns/${campaignId}/publish`); return validateResponse(BusinessCampaignSchema, data, 'publishBusinessCampaign'); }
export async function getCampaignReactions(workspaceId: string, campaignId: string, filter: 'newest' | 'selected') { const { data } = await api.get<unknown>(`/businesses/${workspaceId}/campaigns/${campaignId}/reactions`, { params: { filter } }); return validateResponse(CampaignReactionPageSchema, data, 'getCampaignReactions'); }
export async function setReactionSelected(workspaceId: string, campaignId: string, reactionId: string, selected: boolean) { if (selected) await api.put(`/businesses/${workspaceId}/campaigns/${campaignId}/reactions/${reactionId}/selection`); else await api.delete(`/businesses/${workspaceId}/campaigns/${campaignId}/reactions/${reactionId}/selection`); }
