import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import * as businessApi from '@/services/api/businesses';
import { queryKeys } from '@/services/queryKeys';

export function useMyBusiness() { return useQuery({ queryKey: queryKeys.business.mine, queryFn: businessApi.getMyBusiness, retry: false }); }
export function useBusinessOverview(workspaceId?: string) { return useQuery({ queryKey: queryKeys.business.overview(workspaceId ?? ''), queryFn: () => businessApi.getOverview(workspaceId!), enabled: !!workspaceId, refetchInterval: (query) => query.state.data?.activeCampaign?.state === 'publishing' ? 3000 : false }); }
export function useBusinessCampaigns(workspaceId?: string) { return useQuery({ queryKey: queryKeys.business.campaigns(workspaceId ?? ''), queryFn: () => businessApi.getCampaigns(workspaceId!), enabled: !!workspaceId }); }
export function useCreateCampaign(workspaceId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (input: { title: string; mediaUrl: string; mediaType: 'image' | 'video'; textOverlay?: string }) => businessApi.createCampaign(workspaceId, input), onSuccess: () => { client.invalidateQueries({ queryKey: queryKeys.business.campaigns(workspaceId) }); client.invalidateQueries({ queryKey: queryKeys.business.overview(workspaceId) }); } }); }
export function usePublishCampaign(workspaceId: string) { const client = useQueryClient(); return useMutation({ mutationFn: (campaignId: string) => businessApi.publishCampaign(workspaceId, campaignId), onSuccess: () => { client.invalidateQueries({ queryKey: queryKeys.business.campaigns(workspaceId) }); client.invalidateQueries({ queryKey: queryKeys.business.overview(workspaceId) }); } }); }
export function useCampaignReactions(workspaceId?: string, campaignId?: string, filter: 'newest' | 'selected' = 'newest') { return useQuery({ queryKey: queryKeys.business.reactions(workspaceId ?? '', campaignId ?? '', filter), queryFn: () => businessApi.getCampaignReactions(workspaceId!, campaignId!, filter), enabled: !!workspaceId && !!campaignId }); }
export function useReactionSelection(workspaceId: string, campaignId: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ reactionId, selected }: { reactionId: string; selected: boolean }) => businessApi.setReactionSelected(workspaceId, campaignId, reactionId, selected), onSuccess: () => client.invalidateQueries({ queryKey: queryKeys.business.reactions(workspaceId, campaignId, 'newest') }) }); }
